### ISSUE TITLE
Make Swedish postcode locale

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/coronastatus#2]
In `coronastatus/app/locales/` need to make `sv-municipalities.json` and `sv-postalCodeCoordinates.json` files with Swedish postcodes and their lat/lng locations.

**Comment by michaelmcmillan** [comment]
Hey! I can help with this, we have a handy script for pulling this stuff automatically

**Comment by michaelmcmillan** [comment]
https://github.com/BustByte/coronastatus/pull/319

**Comment by ewels** [comment]
Hi @michaelmcmillan - that would be great!

@jhagberg dug up a few potential data sources:

* http://insamling.postnummeruppror.nu/nightly/
* https://www.geonames.org/countries/SE/sweden.html
* http://download.geonames.org/export/zip/SE.zip

But I don't know how far he / @pontus / anyone has come with using these to make the JSON files.

**Comment by ewels** [comment]
> BustByte#319

Awesome! 😆

**Comment by michaelmcmillan** [comment]
The file you referenced [SE.zip](http://download.geonames.org/export/zip/SE.zip) is what we feed [this script](https://github.com/BustByte/coronastatus/blob/master/app/locales/geonames-converter.py) in our repo ☺️

**Comment by ewels** [comment]
> List of postal code coordinates (we have a script for this).

Should have spotted this in the readme sorry. Nice!

**Comment by michaelmcmillan** [comment]
I'm not even sure if it's in the readme. I'll add it!

**Comment by jhagberg** [comment]
Grejt tusen tack!
